FROM bennu/jobs:missing

RUN mkdir /usr/local/bin/missing

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# cd /home/ubuntu/bennu_jobs_missing
# build -t bennu_jobs_missing .
# docker run -it -d bennu_jobs_missing

#docker run -it --entrypoint "/bin/bash" bennu/jobs:missing



